spring.main.banner-mode=off
spring.datasource.initialization-mode=always
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://bahmni-standard-insurancedb-1:5432/insurance
spring.datasource.username=insurance
spring.datasource.password=insurance

#Postgres Driver
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=false
logging.level.root=INFO
log4j.config.file=log4j.properties
server.port=8092
server.servlet.context-path=/insurance-integration/

dummy.claimResponse.url=http://hapi.fhir.org/baseDstu3/ClaimResponse/1463597/_history/1?_format=json
dummy.eligibilityResponse.url=http://hl7.org/fhir/STU3/eligibilityresponse-example-benefits.json
dummy.claimTrack.url= http://hl7.org/fhir/STU3/task-example1.json

openmrs.odoo.api=http://bahmni-standard-openmrs-1:8080/openmrs/ws/rest/v1/patient
odoo.host=192.168.56.101
odoo.port=8069
odoo.database=odoo
odoo.user=admin
odoo.password=admin

imisconnect.user=admin
imisconnect.password=haha
imisconnect.errortrace.include=true
imisconnect.claimresource.save=true
imisconnect.eligresource.save=true

# openimis.healthFacility.id=7e36a5e0-4bc6-4d6c-b4e6-cb20f3093845
# openimis.api.url=http://imis.hib.gov.np/api/api_fhir/
# openimis.api.user=parthf
# openimis.api.password=6UInP3pExG6mgsNJ3vx9
# openimis.api.remote.user=parfhir
# openimis.enterer.id=3b01d6a8-c531-4190-b5c8-86de0f0121fd
# openimis.fhir.api.elig.policy.enabled=http://imis.hib.gov.np/api/api_fhir/EligibilityRequest/
# openimis.fhir.api.elig=http://imis.hib.gov.np/api/api_fhir/EligibilityRequest/
# openimis.fhir.api.claim=http://imis.hib.gov.np/api/api_fhir/Claim/
# openimis.fhir.api.refund=http://imis.hib.gov.np/api/api_fhir/refund/
# openimis.policy.enabled=true

openimis.healthFacility.id=1ac457d3-efd3-4a67-89b3-bf8cbe18045d
openimis.api.url=https://imislegacy.hib.gov.np/api/api_fhir/
openimis.api.user=testuser
openimis.api.password=f/\N6k@67
openimis.api.remote.user=hib_testuser_testfhir
openimis.enterer.id=7aa79c53-057e-4e77-8576-dfcfb03584a8
openimis.fhir.api.elig.policy.enabled=https://imislegacy.hib.gov.np/api/api_fhir/EligibilityRequest/
openimis.fhir.api.elig=https://imislegacy.hib.gov.np/api/api_fhir/EligibilityRequest/
openimis.fhir.api.claim=https://imislegacy.hib.gov.np/api/api_fhir/Claim/
openimis.fhir.api.refund=https://imislegacy.hib.gov.np/api/api_fhir/refund/
openimis.policy.enabled=true

openmrs.root.url=http://bahmni-standard-openmrs-1:8080/openmrs/ws/rest/v1
openmrs.fhir.url=http://bahmni-standard-openmrs-1:8080/openmrs/ws/fhir2/R3
openmrs.user=admin
openmrs.password=Admin123

openmrs.db.url=jdbc:mysql://bahmni-standard-openmrsdb-1:3306/openmrs?user=openmrs-user&password=password
# openelis.db.url=jdbc:mysql://bahmni-standard-openmrsdb-1:3306/openmrs?user=openmrs-user&password=password

# HikariCP settings
# 60 sec
spring.datasource.hikari.connection-timeout=60000
# max 5