name: Insurance Integration Docker Image CI/CD

on:
  push:
    branches: ["develop"]

  pull_request:
    branches: ["main"]

jobs:

  build:
    if: github.ref_name == 'develop' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v7
        with:
          image: rijan17/insurance-integration-cicd
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    if: github.base_ref == 'main' && github.event_name == 'pull_request'
    runs-on: self-hosted

    steps:
      - name: Pull latest docker image
        run: |
          cd /home/rijan/bahmni-docker/bahmni-standard
          docker compose pull insurance-integration
          docker compose up -d insurance-integration

      - name: Clean unused Docker images
        run: |
          docker images "rijan17/insurance-integration-cicd" \
          --filter "dangling=true" \
          -q | xargs -r docker rmi

      - name: Verify deployment
        run: |
          docker ps --filter "name=insurance-integration"
     
